export const pakistanCities = [
  { value: "Karachi", label: "Karachi" },
  { value: "Lahore", label: "Lahore" },
  { value: "Faisalabad", label: "Faisalabad" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "Islamabad", label: "Islamabad" },
  { value: "Multan", label: "Multan" },
  { value: "Gujranwala", label: "Gujranwala" },
  { value: "Peshawar", label: "Peshawar" },
  { value: "Quetta", label: "Quetta" },
  { value: "Sialkot", label: "Sialkot" },
  { value: "Bahawalpur", label: "Bahawalpur" },
  { value: "Sargodha", label: "Sargodha" },
  { value: "Sukkur", label: "Sukkur" },
  { value: "Jhang", label: "Jhang" },
  { value: "Sheikhupura", label: "Sheikhupura" },
  { value: "Larkana", label: "Larkana" },
  { value: "Gujrat", label: "Gujrat" },
  { value: "Mardan", label: "Mardan" },
  { value: "Kasur", label: "Kasur" },
  { value: "Rahim Yar Khan", label: "Rahim Yar Khan" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Okara", label: "Okara" },
  { value: "Wah", label: "Wah" },
  { value: "Dera Ghazi Khan", label: "Dera Ghazi Khan" },
  { value: "Mirpur Khas", label: "Mirpur Khas" },
  { value: "Nawabshah", label: "Nawabshah" },
  { value: "Mingora", label: "Mingora" },
  { value: "Bannu", label: "Bannu" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "Hafizabad", label: "Hafizabad" },
  { value: "Kohat", label: "Kohat" },
  { value: "Jacobabad", label: "Jacobabad" },
  { value: "Shikarpur", label: "Shikarpur" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Gojra", label: "Gojra" },
  { value: "Bahawalnagar", label: "Bahawalnagar" },
  { value: "Abbottabad", label: "Abbottabad" },
  { value: "Muridke", label: "Muridke" },
  { value: "Pakpattan", label: "Pakpattan" },
  { value: "Khuzdar", label: "Khuzdar" },
  { value: "Jaranwala", label: "Jaranwala" },
  { value: "Chishtian", label: "Chishtian" },
  { value: "Daska", label: "Daska" },
  { value: "Dadu", label: "Dadu" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Ahmadpur East", label: "Ahmadpur East" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Tando Adam", label: "Tando Adam" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Vehari", label: "Vehari" },
  { value: "Nowshera", label: "Nowshera" },
  { value: "Bara Kahu", label: "Bara Kahu" },
  { value: "Jalalpur", label: "Jalalpur" },
  { value: "Chakwal", label: "Chakwal" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Kandhkot", label: "Kandhkot" },
  { value: "Hasilpur", label: "Hasilpur" },
  { value: "Sadiqabad", label: "Sadiqabad" },
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Fatehpur", label: "Fatehpur" },
  { value: "Turbat", label: "Turbat" },
  { value: "Burewala", label: "Burewala" },
  { value: "Haripur", label: "Haripur" },
  { value: "Shahkot", label: "Shahkot" },
  { value: "Nawabganj", label: "Nawabganj" },
  { value: "Mansehra", label: "Mansehra" },
  { value: "Shujaabad", label: "Shujaabad" },
  { value: "Rahim Yar Khan", label: "Rahim Yar Khan" },
  { value: "Bannu", label: "Bannu" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "Hafizabad", label: "Hafizabad" },
  { value: "Kohat", label: "Kohat" },
  { value: "Jacobabad", label: "Jacobabad" },
  { value: "Shikarpur", label: "Shikarpur" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Gojra", label: "Gojra" },
  { value: "Bahawalnagar", label: "Bahawalnagar" },
  { value: "Abbottabad", label: "Abbottabad" },
  { value: "Muridke", label: "Muridke" },
  { value: "Pakpattan", label: "Pakpattan" },
];
